server:
  port:
    8080
spring:
  application:
    name: ticket-booking-api
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket-booking
    username: coder
    password: Mohitsom29
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE





